### ISSUE TITLE
Release preparation works

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_devices#4]
- [x] : Pub/Sub should be local. Remove leading `/` on pub sub.
- [x] :  link license on top of each python files except third party module. 

Example :  https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_utilities/src/rocon_app_utilities/indexer.py

license link : https://raw.githubusercontent.com/robotics-in-concert/rocon_devices/license/LICENSE
- [x] : migrate msgs into rocon_msgs as independent package (rocon_msgs/rocon_device_msgs :+1:).
- [x] : update package.xml. license, maintainer, author, url. 

Example: https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_utilities/package.xml
- [x] : clean up CMakeLists.txt
- add roslint
- local bin install rule for roshue_bridge.py

Example : https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_utilities/CMakeLists.txt
- [x] : cleanup setup.py. No global script installation.
- [x] : a `rocon_devices` metapackage for releasing.

Example:  https://github.com/robotics-in-concert/rocon_app_platform/tree/hydro-devel/rocon_app_platform
- [x] : rename package to `rocon_hue`

**Comment by stonier** [comment]
Licenses is a good point - what's the license of this third party module?

**Comment by jihoonl** [comment]
> Licenses is a good point - what's the license of this third party module?

It is GWTFPL - http://www.wtfpl.net

**Comment by dwlee** [comment]
I fix issues.
But for testing issue about `migrate msgs into rocon_msgs as independent package.`,need to `rocon_devices_msg`
(I made already 6e91df8f5eedf84eb65b038fd4dfe6672dc9c084, waitting PR)

**Comment by stonier** [comment]
@dwlee Where is that link pointing to (it's broken right now)?

**Comment by jihoonl** [comment]
Pull request #8 has been merged.
