### ISSUE TITLE
roshue causes install to fail

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_devices#9]
Calling yujin_make --install (or catkin_make --install) fails when installing roshue:

```
running build_scripts
creating /opt/rocon_workspace/build/rocon_devices/roshue/scripts-2.7
error: scripts: Is a directory
CMake Error at rocon_devices/roshue/catkin_generated/safe_execute_install.cmake:4 (message):

  execute_process(/opt/rocon_workspace/build/rocon_devices/roshue/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  rocon_devices/roshue/cmake_install.cmake:36 (INCLUDE)
  cmake_install.cmake:191 (INCLUDE)


make: *** [install] Error 1
Invoking "make" failed
```

The error is here: https://github.com/robotics-in-concert/rocon_devices/blob/hydro-devel/roshue/setup.py#L9

In case you don't really want a globally visible script for roshue (what I assume) then just remove this line compeletly.  Otherwise you have to specify the script here, not the folder.

**Comment by jihoonl** [comment]
#8 pull request should solve the installation error.
